import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './design-system/tokens.css'
import './styles.css'
import './pages/dashboard.css'
import './pages/access-management.css'
import './pages/customers.css'
import './pages/activity-logs.css'
import './pages/areas-tables.css'
import './pages/table-operations.css'
import './pages/reservations.css'
import './pages/shifts-scheduling.css'
import './pages/menu-management.css'
import './pages/orders.css'
import './pages/kitchen.css'
import './pages/payments.css'
import './pages/invoices.css'
import './pages/revenue-reports.css'
import './pages/table-qr-codes.css'
import './pages/qr-order.css'
import './pages/restaurant-settings.css'
import './pages/restaurant-settings-modal-fix.css'
import './pages/promotions.css'
import './pages/inventory.css'
import './pages/auth-security.css'
import './pages/module-loading.css'
import './design-system/admin.css'
import './components/notification-center.css'
import './pages/dashboard-command-center.css'
import './pages/dashboard-calendar-fix.css'
import './pages/orders-dark-overrides.css'
import './pages/orders-overlay-polish.css'
import './pages/orders-modal-overflow-fix.css'
import './pages/kitchen-dark-overrides.css'
import './pages/payments-dark-overrides.css'
import './pages/payments-confirm-fix.css'
import './pages/employees-dark.css'
import './pages/customers-dark.css'
import './pages/shifts-dark.css'
import './pages/access-dark.css'
import './pages/invoices-dark.css'
import './pages/revenue-dark.css'
import './pages/activity-logs-dark.css'
import './pages/activity-logs-hover-fix.css'
import './pages/areas-tables-dark.css'
import './design-system/confirm-dialog-polish.css'
import './pages/areas-tables-final-fix.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
